### ISSUE TITLE
DECIMAL overflow - false positive on ROW/COLUMN

### ISSUE THREAD

**Issue by LievenDeFoor** [Riverside-Software/sonar-openedge#1028]
![afbeelding](https://user-images.githubusercontent.com/8639525/222150056-92f14648-d8ab-4319-bfeb-bed62a8900c1.png)

ROW and COLUMN are decimal, so why the warning here?

Idem when setting HEIGHT-CHARS/WIDTH-CHARS

**Comment by LievenDeFoor** [comment]
Idem when setting HEIGHT-CHARS/WIDTH-CHARS

**Comment by gquerret** [comment]
Right, those attributes are defined as `INT` in the expression engine. Will fix that.

**Comment by gquerret** [comment]
All those properties were marked as `INTEGER` instead of `DECIMAL`:
* BORDER-BOTTOM-CHARS
* BORDER-LEFT-CHARS
* BORDER-RIGHT-CHARS
* BORDER-TOP-CHARS
* COLUMN
* EDGE-CHARS
* FULL-HEIGHT-CHARS
* FULL-WIDTH-CHARS
* GRID-UNIT-HEIGHT-CHARS
* GRID-UNIT-WIDTH-CHARS
* HEIGHT-CHARS
* MAX-HEIGHT-CHARS
* MAX-WIDTH-CHARS
* MIN-COLUMN-WIDTH-CHARS
* MIN-HEIGHT-CHARS
* MIN-WIDTH-CHARS
* ROW
* ROW-HEIGHT-CHARS
* VIRTUAL-HEIGHT-CHARS
* VIRTUAL-WIDTH-CHARS
* WIDTH-CHARS

**Comment by gquerret** [comment]
Fixed in develop
