### ISSUE TITLE
False positives on unused variables

### ISSUE THREAD

**Issue by KWSMaster** [Riverside-Software/sonar-openedge#123]
2 classes of issue here:

`DEFINE (type) PARAMETER x AS ...`
- this comes up with API call backs quite a bit. You define a procedure for callback that has required parameters, but those parameters are irrelevant to your usage. We have a lot of legacy code with this pattern.

`DEFINE NEW SHARED VARIABLE ...`
- very often in legacy code you're setting up the shared variables in an entrance module, and never use them, since your external sub-procedures are the users. In the definition module, they should not be counted towards unused variable rules.

**Comment by movedoa** [comment]
I don't think any of these are false positives.
The first issue can be solved with method polymorphism.
The second issue can be solved if you don't use shared variables which are bad practice and shouldn't be used.

So imho both issues happen only in "bad" code that should be refactored and thus are correct.

**Comment by gquerret** [comment]
For my own information, are you a paid customer (as it's the first time this GitHub login is being used) ? Please just send an email to g.querret@riverside-software.fr
That's only in order to assign priority to issues, you would still have an answer. And if you're just evaluating, you may not want to disclose who you are, that will be OK too !

**Comment by KWSMaster** [comment]
First issue is common in non-object code. Since we have thousands of modules with this issue, it's EXTREMELY false positive for our code base. The most recent case of this is in callback logic from the STOMP objects from dotr.

The second issue is relevant for a code base that was started in V4 of Progress. Again, thousands of modules that are written with the pattern of entry procedure creates new shared variables, and external sub procedure modules reference them.

I understand that you feel this type of code is "bad" -- but it's NOT "bad" within it's design. Refactoring for shared variables is a valid issue for modernization, but not for managing a legacy code base.

**Comment by movedoa** [comment]
Just because you have thousands of issues doesn't make it a false positive.
Bbeing legacy code doesnt make it less of an issue either.
If the variable is not used than it will report on it.

You could always split you legacy code in a seperate sonar project and disable this rule but this is an issue with you code not with the analyzer.

The rule works like it should.

**Comment by KWSMaster** [comment]
OK, I don't see how this tool will be very useful in our code base then.

**Comment by gquerret** [comment]
For the first entry, I'd also consider that's not a false positive, but the fact is you have so many issues for this rule that you can't find anything else, so it's just that the signal to noise ratio is very bad. How can we make this ratio better :
* It's possible to completely disable the rule, but you wouldn't see what you consider real issues
* It's possible to use preprocessor (`{&_proparse_ prolint-nowarn(varusage)}`) to discard specific issues ; probably a bit too long on legacy code
* It will be possible in the future to add annotations to skip entire code blocks, something à la @java.lang.SuppressWarnings()
 * It's possible to mark issues as false positive directly in the SonarQube UI ; if you find a pattern for this kind of issue, you can select multiple issues at once and mark them. Still a bit long for legacy code 
* But the best idea is certainly to split the rule in multiple ones ; instead of having a single rule 'Unused variable', we could have 'Unused parameter', 'Unused variable', 'Unusued shared variable' and so on. So all types of issues would still be reported, but it would be easier to activate / deactivate rules, or filter all the issues in SQ. In this case, it would also be possible to have a better usage of quality profiles, where legacy code could use a 'Legacy quality profile' and new code another QP which would enforce a lot more rules.

For the second problem, `DEFINE SHARED VARIABLE` has to raise an issue if the variable isn't used, while `DEFINE NEW SHARED VARIABLE` may not raise an issue (or a different type of issue).

**Comment by gquerret** [comment]
And please also note that the OpenEdge plugin can be extended with your own rules ! Documentation is on its way however, everything will be moved to GitHub (from Confluence).

**Comment by KWSMaster** [comment]
If we can have a way to disable the parameter rule without disabling all unused variable checking I can use that. This issue is critical for us since our reporting system requires 2 input parameters in all reports, but most reports don't use both parameters. Classic Progress ABL procedures cannot be RUN unless all parameters passed are represented in the called module - you get error 3234 and crash. This particular rule applies to 2/3 of our code base.

NEW SHARED is going to be hard to deal with if it's not handled somehow. If this requires a new rule to allow disabling that would fix it for us as well. I think I could fix some of our code base with the preprocessor, but this particular pattern will be common in legacy code, and irrelevant in modern code (you should never used shared variables)

**Comment by gquerret** [comment]
Rules will be split

**Comment by gquerret** [comment]
Fixed in master
