### ISSUE TITLE
Whole index Rule doesn't work for Temp-Tables

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#14]
I just found out that the whole index rule doesn't work for temp-table queries.
I looked in the xref and is says WHOLE-INDEX but i get no errors in sonar for the same sourcecode.

I would guess that the Sort access rule has the same error (but i can't verify that)

**Comment by jakejustus** [comment]
Due to the high number of false positives (not really FP as there's a WHOLE-INDEX on the TT, but the impact is extremely low), it was decided to report WHOLE-INDEX access only on DB tables. It's however possible to have a different rule which will report that on TT. A new version will be released today, not sure if it will be make it in time. Otherwise, you can use the "Custom XREF" rule template to achieve that.

**Comment by movedoa** [comment]
A different rule would be great, thank you

**Comment by jakejustus** [comment]
Included in 1.8.0
