### ISSUE TITLE
Non standard program file extensions

### ISSUE THREAD

**Issue by stroyer** [Riverside-Software/sonar-openedge#28]
We have used non-standard file extensions with ABL code in the past (.tp, .v, etc), including files that do not have an extension at all.  Is there any way to have SonarQube scan files other than those with .p, .w, .i and .cls extensions?  I tried using `sonar.oe.file.suffixes` in the properties file for the command line scanner but that didn’t seem to affect the list of files.  Thanks much.

**Comment by gquerret** [comment]
This issue was fixed in 1.9.3.
The "standard" `sonar.oe.file.suffixes` (that what is available in other languages) property has been implemented. Files without extension can't easily be imported in SonarQube (and that's a SonarQube issue, the plugin can't do anything here) ; the workaround is to include every file in sonar.oe.file.suffixes.
