### ISSUE TITLE
Issues from SonarLint do not appear ?

### ISSUE THREAD

**Issue by jurjendijkstra-vma** [Riverside-Software/sonar-openedge#290]
I am just beginning to configure Sonaqube and SonarLint, I love it already!

This is just a question, maybe it works as designed, maybe not....

When I open a sourcefile in Eclipse then I can see in "SonarLint Console" that issues are fetched from the server. Status is 200, and when I paste the URL in chrome then I receive a whole lot of issues from sonarqube because the sourcefile was already analyzed.

```
fetchServerIssues moduleKey=nl.vanmeijel:metacom-do-openedge, filepath=src/do/doresnrm.p
GET 200 http://mysonarqube:9000/batch/issues?key=nl.vanmeijel%3Ametacom-do-openedge%3Asrc%2Fdo%2Fdoresnrm.p | time=23ms
```

So I thought that the fetched issues would show up in the "SonarLint Issue Locations" view and would create markers in the procedure editor. But nothing seems to happen? Is that as designed, or am I doing something wrong?

**Comment by gquerret** [comment]
SonarLint only displays issues when a file is saved. Issues are however fetched from the server in order to know if an issue is marked as "won't fix" for example.
So when you save your file, the SonarLint console should display:
```
SonarLint analysis of file /path/to/filename.p...
Found xxx issue(s)
```

You can enable verbose log and analysis log in this console if you want to know what happens on the Eclipse side.

**Comment by jurjendijkstra-vma** [comment]
ah, I understand. Thanks!
