### ISSUE TITLE
FIND and GET EXCLUSIVE-LOCK without NO-WAIT on TEMP-TABLE

### ISSUE THREAD

**Issue by maelstraggiotti** [Riverside-Software/sonar-openedge#374]
Shouldn't the "FIND and GET EXCLUSIVE-LOCK without NO-WAIT rule" be excluded for TEMP-TABLEs as locking is unnecessary ?

Thanks

**Comment by movedoa** [comment]
I consider this good practice. It is nice to see in the FIND statement if the program changes data or not.

**Comment by stefandrissen** [comment]
Then I would use a comment, which provides exactly the same information instead of a statement that implies doing something it doesn't.

**Comment by gquerret** [comment]
As we can see in the latest bug reports, there's no one size fits all. We'll introduce options as much as possible in order to address the different cases, or split the rule in multiple ones (and quality profiles management will allow activating any of the different variations).

@maelstraggiotti On the issue by itself, yes, it's possible to detect this case

**Comment by maelstraggiotti** [comment]
A rule parameter would be perfect to cope with our existing habits.

**Comment by gquerret** [comment]
Parameter added in master
