### ISSUE TITLE
Unnecessary init value in variable definition

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#514]
A rule that flags unnecessary init values in variable definitions would be nice.
I see no value in defining an init value that is the default value anyway.

Examples:
```
DEFINE VARIABLE lcFoo AS CHARACTER NO-UNDO INIT "":U.
DEFINE VARIABLE liFoo AS INTEGER NO-UNDO INIT 0.
DEFINE VARIABLE ldFoo AS DECIMAL NO-UNDO INIT 0.0.
```

**Comment by stefandrissen** [comment]
+1

Also a rule for :u on an empty string. :-)

Although it may make a difference when using "a":u + "":u + "b":u since the compiler then reduces this to "ab":u - so let's open the can of worms for including nonsensical values in expressions:

def var ii as int no-undo.
def var cc as char no-undo.

ii = ii + 0.
cc = cc + "".

:-)

**Comment by jurjendijkstra** [comment]
-1 
why? Setting an initial value (which equals to the language default) has no risk or performance degradation, there is no expectation that the programmer probably made a mistake as with "statement has no effect" rule and it will not confuse any colleague who is going to read the code. It seems to me that this rule would just add waste time and create unnecessary noise in the Sonarqube output.

**Comment by gquerret** [comment]
Merged in develop, will be part of next release. Not included in the default quality profile.
