### ISSUE TITLE
SonarLint Rule Description is showing wrong severity

### ISSUE THREAD

**Issue by lneumeier** [Riverside-Software/sonar-openedge#640]
I changed for a custom Quality Profile the severity of unused buffers from major to minor. The View "SonarLint On-The-Fly" is showing the correct severity (Minor), but the View "SonarLint Rule Description" is showing for "Unused buffer" the severity major (possibly from the Quality Profile extended sonarway).

My custom Quality Profile is set as default.

**Comment by gquerret** [comment]
I'll investigate, but that probably will be forwarded to SonarQube as this view is not handled by the OE plugin.

**Comment by gquerret** [comment]
The severity displayed in the rule description is the one which is hard-coded in every rule (Java, OpenEdge, ...). As multiple quality profiles can live in a single Eclipse workspace (due to multiple projects), it wouldn't be possible to know which severity to display. As opposed to the "On-the-fly" view which display files from a project, thus associated with a quality profile.
