### ISSUE TITLE
Hard coded credentials: practical?

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#790]
While I think it is correctly flagging this:

    function checkUser returns logical private (
       i_cuser_id as character,
       i_cpassword as character
    ):
    
       return setuserid( i_cuser_id, i_cpassword, "db" ).

    end function.

This is flagged as:

Variable definition i_cpassword should not include_d_ hard-coded credentials

So it seems to be expecting me to trace back all users of this function to see if they are not somehow passing a hard coded value?

**Comment by gquerret** [comment]
Yes, it detects that the variable i_cpassword (name of the variable triggers the rule here) is passed directly from function parameter to another function. So the [security hotspot](https://docs.sonarqube.org/latest/user-guide/security-hotspots/) highlight this code usage to be reviewed.
Unfortunately, we can't efficiently track usage of this function, first because of the cost in CPU / memory (although that can be improved), but mostly because of dynamic code (dynamic-function, run value(), publish / subscribe) that will always leave holes in the detection process.

And typo fixed! I thought at first it was some MarkDown issue :-)

**Comment by stefandrissen** [comment]
So the /name/ of the parameter is triggering the rule? 
Can this be added to the explanation of the rule, since that only contains:

    Several statements such as CONNECT should be checked for the -U and -P parameters.

    Sensitive code example
      CONNECT "-db foo -H localhost -S 12000". // Questionable, no username and password in the DB

**Comment by gquerret** [comment]
Description will be improved. This OE rule is based on the [Java rule](https://rules.sonarsource.com/java/type/Security%20Hotspot/RSPEC-2068).

**Comment by stefandrissen** [comment]
Thanks.
