### ISSUE TITLE
Is it possible to differentiate between rules in SonarLint on the fly & Sonarqube server

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#797]
Example use case "Trailing white space".

Should be flagged when editing, but is IMHO more a misconfiguration of the editor than a real issue in the source.

I'd like to keep the rule active but only for sonarlint on the fly

**Comment by gquerret** [comment]
You could do that by associating your PDSOE project to a different SonarQube project, in turn associated to a different quality profile. But you'd lose all the issues which have been marked as false positive or won't fix, so that's far from perfect.
Unfortunately, once the project is bound to a SQ server, you can't change the configuration in SonarLint. The only other solution is to modify how rules are written to limit them to SQ or SL.

**Comment by cverbiest** [comment]
OK, thank you for the info.

I'll close the call.
