### ISSUE TITLE
Is it possible to construct AST for a progress(.p) file when it gives compilation errors?

### ISSUE THREAD

**Issue by kush96** [Riverside-Software/sonar-openedge#804]
I was exploring proparse java API to create AST for my .p files and subsequently traverse those . I was using the following cod for it 

```
          parser = new DoParse(pFilePath);
          parser.doParse();
          JPNode topNode = parser.getTopNode();
          walkTree()
```
The method walkTree can be described as below
```
  private static int indent =0;
  static void walkTree(JPNode node){
        if(node==null)
                return;
        for(int i = 0;i<indent;i++)
                System.out.print(" ");
        System.out.println(node);
        indent++;
         if(node.getType()==IF){
                indent = indent;
         }
         for(int i =0;i<node.getDirectChildren().size();i++){
          walkTree(node.getDirectChildren().get(i));
    }
    indent--;
  }
```
I keep getting thrown exceptions while calling `parser.doParse();` which are expected like 'missing include file' or 'unexpected token' . Is there someway possible through current API where during AST creation, only nodes for which compilation fail are excluded  from AST?

**Comment by gquerret** [comment]
The DoParse object doesn't exist anymore, so you're using an old version of Proparse. You should use ParseUnit which wraps the lexer, preprocessor and parser.
It's currently not possible to generate the AST without expanding include files. You should create the RefactorSession object with the right propath, so that include files can be correctly expanded.
