### ISSUE TITLE
Compatibility SonarQube 9.5

### ISSUE THREAD

**Issue by dominickdm** [Riverside-Software/sonar-openedge#972]
We are planning to do an upgrade on our Sonar server (currently 7.9). We are using SQ to do code analysis of OE 11.7 and OE 12.2.

Question: is SonarQube 9.5 supported with the OE plugin? In the wiki i read "The OpenEdge plugin is supported on 7.6+ and 8.2+. The recommended version is 8.9.". So, theoretically it should be fine, but i wonder if this was tested with SQ 9.5. Maybe the wiki should be updated to mention the latest tested SQ version?

Thank you

**Comment by stefandrissen** [comment]
An earlier question regarding support of SonarQube 9.1: https://github.com/Riverside-Software/sonar-openedge/issues/918

**Comment by gquerret** [comment]
9.5 was released a couple days ago, so this version has not been tested yet. I'll update this ticket as soon as this is done.

sonar.riverside-software.fr is running the LTS version (8.9), and an internal Sonar instance is running 9.3. The dev instance on my machine is running 9.4. All of them without issues, **except** if you're running SonarLint with PDSOE 11.7 (no problem with Sonar scanner running on a CI server) ; PDSOE 11.7 support will stop soon due to Java 8.

Updating [Sonar Scanner](https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/) is sometimes required when updating the Sonar server (SonarSource doesn't provide a compatibility matrix AFAIK).

**Comment by dominickdm** [comment]
Thank you for the feedback!

> PDSOE 11.7 support will stop soon due to Java 8.

Just to be clear, does this mean that in one of the next sonar-openedge-plugin releases, we won't be able to use SonarLint from PDSOE 11.7 anymore?

**Comment by gquerret** [comment]
Wiki page has been updated ; no issues have been found with SonarQube 9.5 (even with PDSOE 11.7)
